language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
    - pip install -r requirements.txt -r tests/requirements.txt
script:
    - pytest --cov=. --cov-config=.coveragerc --cov-report=term-missing
after_success:
    - bash <(curl -s https://codecov.io/bash)
