language: python
install:
    - python setup.py install
    - pip install tox
script:
    - tox
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
after_success:
    - bash <(curl -s https://codecov.io/bash)
